name: build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v*.**
  merge_group:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  CARGO_TERM_COLOR: always

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      msrv-version: ${{ steps.get-versions.outputs.msrv-version }}
      stable-version: ${{ steps.get-versions.outputs.stable-version }}
      git-version: ${{ steps.get-versions.outputs.git-version }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
          fetch-depth: 0
          fetch-tags: true
      - name: Update rustup
        run: rustup update stable --no-self-update
      - name: Format check
        run: |
          rustup component add rustfmt
          cargo fmt --all -- --check -l
      - name: Extract versions
        id: get-versions
        run: |
          MSRV=$(cargo metadata --no-deps --format-version=1 --locked | jq -r '.packages[0].rust_version')
          echo "msrv-version=$MSRV" >> $GITHUB_OUTPUT
          STABLE_VERSION=$(rustc +stable --version | awk '{print $2}')
          echo "stable-version=$STABLE_VERSION" >> $GITHUB_OUTPUT
          GIT_VERSION=$(git describe --tags)
          echo "git-version=$GIT_VERSION" >> $GITHUB_OUTPUT
      - name: Publish dry-run 
        run: |
          cargo publish --dry-run -p csaf-rs --verbose --no-verify --locked

  build-matrix:
    needs: prepare
    permissions:
      contents: write
    strategy:
      matrix:
        version: 
          - ${{ needs.prepare.outputs.msrv-version }}
          - ${{ needs.prepare.outputs.stable-version }}
        target:
          - arch: x86_64-unknown-linux-gnu
            runs-on: ubuntu-latest
          - arch:  aarch64-unknown-linux-gnu
            runs-on: ubuntu-24.04-arm
          - arch: aarch64-apple-darwin
            runs-on: macos-latest
          - arch: x86_64-apple-darwin
            runs-on: macos-latest
          - arch: x86_64-pc-windows-msvc
            runs-on: windows-latest
            ext: .exe
          - arch: wasm32-wasip2
            runs-on: macos-latest
            skip-test: true
            ext: .wasm
    runs-on: ${{ matrix.target.runs-on }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Use cache
        id: rust-cache
        uses: Swatinem/rust-cache@v2
        with:
          key: build-${{matrix.version}}-${{ matrix.target.arch }}-${{ needs.prepare.outputs.git-version }}
      - name: Update rustup
        if: steps.rust-cache.outputs.cache-hit != 'true'
        run: rustup update stable --no-self-update
      - name: Set Rust version
        if: steps.rust-cache.outputs.cache-hit != 'true'
        run: |
          rustup override set ${{ matrix.version }}
          rustup default ${{ matrix.version }}
      - name: Prepare target
        if: steps.rust-cache.outputs.cache-hit != 'true'
        run: rustup target add ${{ matrix.target.arch }}
      - name: Install clippy
        if: ${{ matrix.target.arch != 'wasm32-wasip2' && steps.rust-cache.outputs.cache-hit != 'true' }}
        run: |
          # this is necesary because clippy ignores the target flag
          rustup component add clippy 
          rustup component add --toolchain ${{ matrix.version }}-${{ matrix.target.arch }} clippy
      - name: Install cargo-auditable
        if: steps.rust-cache.outputs.cache-hit != 'true'
        run: cargo install cargo-auditable --locked
      - name: Update assets
        run: ./update_assets.sh
      - name: Check compilation
        run: cargo check --locked --target=${{ matrix.target.arch }} --verbose
      - name: Clippy check
        if: ${{ matrix.target.arch != 'wasm32-wasip2' }}
        run: cargo clippy --all-targets --locked --target=${{ matrix.target.arch }} -- -D warnings
      - name: Build
        run: cargo auditable build --locked --target=${{ matrix.target.arch }} --release --verbose
      - name: Build WASM bindings
        if: ${{ matrix.target.arch == 'wasm32-wasip2' }}
        run: |
            cargo install wasm-pack --locked
            wasm-pack build csaf-rs --scope csaf-rs
      - name: Run tests
        run: cargo test --locked --target=${{ matrix.target.arch }} --verbose
        if: ${{ matrix.target.skip-test != true }}
      - name: Archive csaf-validator (${{ matrix.target.arch }})
        uses: actions/upload-artifact@v4
        with:
          name: csaf-validator-${{ matrix.target.arch }}-${{ matrix.version }}-${{ needs.prepare.outputs.git-version }}
          path: target/${{ matrix.target.arch }}/release/csaf-validator${{ matrix.target.ext }}
      - name: Generate CycloneDX SBOM
        uses: anchore/sbom-action@v0
        with:
          file: ./target/${{ matrix.target.arch }}/release/csaf-validator${{ matrix.target.ext }}
          format: cyclonedx-json
          artifact-name: csaf-validator_${{ matrix.target.arch }}_${{ matrix.version }}_${{ needs.prepare.outputs.git-version }}_sbom.cdx.json
      - name: Generate SPDX SBOM
        uses: anchore/sbom-action@v0
        with:
          file: ./target/${{ matrix.target.arch }}/release/csaf-validator${{ matrix.target.ext }}
          format: spdx-json
          artifact-name: csaf-validator_${{ matrix.target.arch }}_${{ matrix.version }}_${{ needs.prepare.outputs.git-version }}_sbom.spdx.json


  build-platforms:
    needs: build-matrix
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check build status
        run: |
          if [ ${{ needs.build-matrix.result }} == 'success' ]; then
            echo "All matrix builds succeeded."
          else
            echo "Some matrix builds failed."
            exit 1
          fi
   
  devguard-secret-scanning: # uses gitleaks
    needs: 
      - prepare
      - build-platforms
    runs-on: ubuntu-latest
    steps:
      - name: Run devguard-scanner secret-scanning
        uses: docker://ghcr.io/l3montree-dev/devguard/scanner:main-latest
        with:
          args: devguard-scanner secret-scanning --assetName=${{ vars.DEVGUARD_ASSET }} --token="${{ secrets.DEVGUARD_TOKEN }}" --defaultRef="${{ needs.prepare.outputs.git-version }}"  --ref="${{ needs.prepare.outputs.git-version }}" --isTag=${{ github.ref_type == 'tag' }}
  devguard-sast: #uses semgrep
    needs: 
      - prepare
      - build-platforms
    runs-on: ubuntu-latest
    steps:
      - name: Run devguard-scanner sast
        uses: docker://ghcr.io/l3montree-dev/devguard/scanner:main-latest
        with:
          args: devguard-scanner sast --assetName=${{ vars.DEVGUARD_ASSET }} --token="${{ secrets.DEVGUARD_TOKEN }}" --defaultRef="${{ needs.prepare.outputs.git-version }}"  --ref="${{ needs.prepare.outputs.git-version }}"  --isTag=${{ github.ref_type == 'tag' }}
  devguard-iac: # uses checkov
    needs: 
      - prepare
      - build-platforms
    runs-on: ubuntu-latest
    steps:
      - name: Run devguard-scanner iac
        uses: docker://ghcr.io/l3montree-dev/devguard/scanner:main-latest
        with:
          args: devguard-scanner iac --assetName=${{ vars.DEVGUARD_ASSET }} --token="${{ secrets.DEVGUARD_TOKEN }}" --defaultRef="${{ needs.prepare.outputs.git-version }}"  --ref="${{ needs.prepare.outputs.git-version }}"  --isTag=${{ github.ref_type == 'tag' }}
  process-sboms:
    needs: 
      - prepare
      - build-platforms
    runs-on: ubuntu-latest
    steps:
      - name: Add Go bin to PATH
        run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
 
      - name: Cache devguard-scanner
        id: cache-scanner
        uses: actions/cache@v4
        with:
          path: ~/go/bin/devguard-scanner
          key: devguard-scanner-${{ runner.os }}
      - name: Install devguard-scanner
        if: steps.cache-scanner.outputs.cache-hit != 'true'
        run: |
          go install github.com/l3montree-dev/devguard/cmd/devguard-scanner@latest
      
      - name: Download all CDX artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: '*sbom.cdx.json'
          path: sboms/
      
      - name: Process CDX files
        run: |
          for cdx_file in $(find sboms -type f -name "*.cdx.json"); do
            echo "Processing: $cdx_file"
            
            # Extract just the filename
            filename=$(basename "$cdx_file")
            
            # Remove prefix and suffix to extract arch and version
            temp=${filename#csaf-validator_}
            temp=${temp%_sbom.cdx.json}
            
            # Split by last dash to separate arch and version
            if [[ $temp =~ ^(.+)_([0-9]+\.[0-9]+\.[0-9]+)_(v.+)$ ]]; then
              arch="${BASH_REMATCH[1]}"
              target="${BASH_REMATCH[2]}"
              version="${BASH_REMATCH[3]}"
            fi

            echo "Architecture: $arch"
            echo "Target: $target"
            echo "Version: $version"

            tagOpt=""

            if [[ ${{ github.ref_type }} == 'tag' ]]; then
              tagOpt="--isTag=true"
            fi

            artifactName="csaf-validator_$arch_$target"
            
            devguard-scanner sbom "$cdx_file" --assetName="${{ vars.DEVGUARD_ASSET }}" --token="${{ secrets.DEVGUARD_TOKEN }}" --artifactName="$artifactName" --defaultRef="$version" --ref="$version" $tagOpt  2>&1
          done

  publish-crates:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write    
    needs:
      - build-platforms
    if: startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, 'beta') && !contains(github.ref, 'alpha')
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Update assets
        run: ./update_assets.sh
      - uses: rust-lang/crates-io-auth-action@v1
        id: auth
      - name: Update rustup
        run: rustup update stable --no-self-update
      - name: Publish
        run: cargo publish --locked -p csaf-rs --verbose
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
      - name: Determine Version
        run: |
          # determine version from tag
          export VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
          if [[ $VERSION != v* ]]
          then
            export VERSION=""
            echo "Building version-less (main or feature branch)"
          else
            echo "Building as ${VERSION}"
          fi
          # store version in GitHub environment file
          echo "version=$VERSION" >> $GITHUB_ENV
      - uses: actions/download-artifact@v4
        with:
          path: csaf-validator
          pattern: csaf-validator-*
      - name: Zip Artifacts
        run: |
          ls csaf-validator | xargs -I {} zip {}.zip -rj csaf-validator/{}
          ls csaf-validator-*.zip
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ env.version }}
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
          files: |
            csaf-validator-*.zip

  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write    
    needs:
      - build-platforms
    if: startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, 'beta') && !contains(github.ref, 'alpha')
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Update assets
        run: ./update_assets.sh
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
      - name: Build WASM bindings
        run: |
          cargo install wasm-pack --locked
          wasm-pack build csaf-rs --scope csaf-rs    
      - name: Publish to NPM
        working-directory: ./csaf-rs/pkg
        run: |
          npm publish --provenance
