name: Make PR for external assets update

on:
  schedule:
    - cron: "15 3 * * 6"

permissions:
  contents: write
  pull-requests: write

jobs:
  execute:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update external assets
        run: ./update_ext_assets.sh

      - name: Create PR
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Update External Assets'
          branch: 'update-external-assets'
          delete-branch: true
          title: 'Update External Assets'